apiVersion: v1
kind: Service
metadata:
  name: sa-frontend-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80  # port forward 80:80
  selector:
    app: sa-frontend  # use pod label here